### ISSUE TITLE
Add a function to store certifcates to IAM as well

### ISSUE THREAD

**Issue by ghost** [shogo82148/acme-cert-updater#336]
S3 is all nice and good, but a function to store the certs to IAM would be great, so it can also be used for ALB and CDN.
Maybe even as an alternative (if Bucket is not defined but IAM is).

See https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_server-certs.html

**Comment by shogo82148** [comment]
ACM https://docs.aws.amazon.com/acm/latest/userguide/acm-overview.html is not supported in your region?
AWS recommends ACM instead IAM if the region supports ACM.

> To enable HTTPS connections to your website or application in AWS, you need an SSL/TLS server certificate. For certificates in a Region supported by AWS Certificate Manager (ACM), we recommend that you use ACM to provision, manage, and deploy your server certificates.

**Comment by Gestahlt** [comment]
It is, but ACM cannot take ACME certs  (Well, except you pay a lot for your own certs) and my problem with ACM is that i cannot get the certificates for other things where i need them. Of course i could also create both certs in ACM and also with ACME, i just found it a bit ugly and rather keep things consistent.
