### ISSUE TITLE
Make the S3 Prefix path - or path in general more sane

### ISSUE THREAD

**Issue by Gestahlt** [shogo82148/acme-cert-updater#339]
The acme updater puts certs in a timestamped bucket. 

While this is okay to see the issuing date and refer to it, a more common path/prefix would be better.

Currently:
`${BUCKET_NAME}/${PREFIX}/${CERT_NAME/${TIMESTAMP}/`

Additional to the current would be nice:
`${BUCKET_NAME}/${PREFIX}/${CERT_NAME}/certs`

would be nice for easier scripting and referencing.

I saw the script and yes.. it will work. But when automating it might be inconvinient.

Example:
When deploying an EC2 with any webserver, you need to fetch the certs with the init script and the `download_certs.sh` script
Alternativly you could use `rclone` to mount the bucket with the certs as read only to a desired location and no longer need to fetch the certs.

**Comment by shogo82148** [comment]
The path design is due to a limitation of S3: S3 cannot atomically replace multiple objects. Fixed path may break the correspondence between private and public keys. `download_certs.sh` prevents this.
